<a href="https://colab.research.google.com/github/Fijiman001/EGR-Empirical-Project/blob/main/data/Final%20data%20for%20the%20study/df_final_and_test_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('merging_done_6.csv')
df.drop(columns=['Company + Kupon and Maturity'], inplace=True)
print(df)

                        Name Clean_Company_Maturity     WKN  \
0       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
1       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
2       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
3       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
4       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
...                      ...                    ...     ...
12622  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
12623  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
12624  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
12625  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
12626  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310

                                                     URL          ISIN  \
0      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
1      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
2      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
3      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
4      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
...                                                  ...           ...
12622  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
12623  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
12624  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
12625  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
12626  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693

         Company Kupon_Maturity  Coupon  Maturity_Start  Maturity_End  \
0        e on se    0 375 20 27   0.375              20            27
1        e on se    0 375 20 27   0.375              20            27
2        e on se    0 375 20 27   0.375              20            27
3        e on se    0 375 20 27   0.375              20            27
4        e on se    0 375 20 27   0.375              20            27
...          ...            ...     ...             ...           ...
12622  talanx ag     1 75 21 42   1.750              21            42
12623  talanx ag     1 75 21 42   1.750              21            42
12624  talanx ag     1 75 21 42   1.750              21            42
12625  talanx ag     1 75 21 42   1.750              21            42
12626  talanx ag     1 75 21 42   1.750              21            42

       is_green  Last Price              DateTime  Volume in Euro  +/- %  \
0             1       94.47  2025-01-02T08:40:00Z             0.0   0,19
1             1       94.37  2025-01-02T10:53:00Z             0.0   0,08
2             1       94.44  2025-01-02T13:47:00Z             0.0   0,16
3             1       94.35  2025-01-03T08:40:00Z             0.0   0,00
4             1       94.24  2025-01-03T11:30:00Z             0.0  -0,11
...         ...         ...                   ...             ...    ...
12622         1       86.17  2025-01-31T08:15:00Z             0.0  -0,07
12623         1       86.27  2025-01-31T10:00:00Z             0.0   0,05
12624         1       86.60  2025-01-31T14:00:00Z             0.0   0,43
12625         1       86.59  2025-01-31T15:00:00Z             0.0   0,42
12626         1       86.69  2025-01-31T16:00:00Z             0.0   0,53

      Currency YTM
0         Euro   -
1         Euro   -
2         Euro   -
3         Euro   -
4         Euro   -
...        ...  ..
12622     Euro   -
12623     Euro   -
12624     Euro   -
12625     Euro   -
12626     Euro   -

[12627 rows x 17 columns]

We do some last data cleaning, removing rows with bad data and rows were prices seem wrong, e.g. last price = 1000

In [2]:
max_last_price = df['Last Price'].max()
max_last_price_row = df[df['Last Price'] == max_last_price]
print(max_last_price_row.count())
df.drop(df[df['Last Price'] == max_last_price].index, inplace=True)

Name                      21
Clean_Company_Maturity    21
WKN                       21
URL                       21
ISIN                      21
Company                   21
Kupon_Maturity            21
Coupon                    21
Maturity_Start            21
Maturity_End              21
is_green                  21
Last Price                21
DateTime                  21
Volume in Euro            21
+/- %                     21
Currency                  21
YTM                       21
dtype: int64

we also interestingly have a good mix of currencies

In [3]:
df['Currency'].unique()

array(['Euro', 'US-Dollar', 'Canadische Dollar', 'Real (Brasilien)',
       'Zloty (Polen)', 'Kolumbianische Pesos', 'Britische Pfund',
       'Neuseeland-Dollar', 'Norwegische Kronen', 'Ungarische Forint',
       'Südafrikanische Rand', 'Australische Dollar', 'Türkische Lira'],
      dtype=object)

# Last merge with additional static data for exact maturity date

In [4]:
df_universe = pd.read_csv('bond_universe_cleaned_1.csv')
print(df_universe.columns)
print(df_universe)

Index(['URL', 'ISIN', 'Company', 'Kupon_Maturity', 'Coupon', 'Maturity_Start',
       'Maturity_End', 'is_green', 'Letzter Preis', 'Veränderung zum Vortag',
       'Letzter Handel', 'Geld', 'Brief', 'Modified Duration', 'Kupon',
       'Emittent', 'Branche', 'Fälligkeit', 'Schuldnerkündigungsart',
       'Sonderkündigung', 'Nachrangig', 'Kleinste handelbare Einheit',
       'Spezialist', 'Handelsmodell', 'Emissionsdatum', 'Emissionsvolumen',
       'Umlaufendes Volumen', 'Emissionswährung', 'Depotwährung',
       'Notierungsaufnahme', 'Emission_year_2020.0', 'Emission_year_2021.0',
       'Emission_year_2022.0', 'Emission_year_2023.0', 'Emission_year_2024.0',
       'Emission_year_2025.0'],
      dtype='object')
                                                    URL          ISIN  \
0     https://www.boerse-frankfurt.de/anleihe/xs2694...  xs2694874533
1     https://www.boerse-frankfurt.de/anleihe/xs2482...  xs2482887879
2     https://www.boerse-frankfurt.de/anleihe/xs2482...  xs2482887879
3     https://www.boerse-frankfurt.de/anleihe/de000a...  de000a3lh6t7
4     https://www.boerse-frankfurt.de/anleihe/de000a...  de000a3lh6t7
...                                                 ...           ...
4068  https://www.boerse-frankfurt.de/anleihe/xs2264...  xs2264087110
4069  https://www.boerse-frankfurt.de/anleihe/xs2293...  xs2293889759
4070  https://www.boerse-frankfurt.de/anleihe/xs2714...  xs2714338592
4071  https://www.boerse-frankfurt.de/anleihe/de000d...  de000dj9akf4
4072  https://www.boerse-frankfurt.de/anleihe/usn307...  usn30706vf42

                                                Company Kupon_Maturity  \
0                               volkswagen-leasing-gmbh     4-75-23-31
1                                                rwe-ag     2-75-22-30
2                                                rwe-ag     2-75-22-30
3               mercedes-benz-international-finance-b-v      3-5-23-26
4               mercedes-benz-international-finance-b-v      3-5-23-26
...                                                 ...            ...
4068                         cooeperatieve-rabobank-u-a     0-01-20-40
4069                         international-finance-corp     6-25-21-28
4070                                     stora-enso-oyj        5-23-28
4071  dz-bank-ag-deutsche-zentral-genossenschaftsban...     3-01-24-39
4072                     enel-finance-international-n-v    2-875-21-41

      Coupon  Maturity_Start  Maturity_End  is_green Letzter Preis  \
0      4.750              23            31         1        106,88
1      2.750              22            30         1         99,19
2      2.750              22            30         1         99,19
3      3.500              23            26         1        101,46
4      3.500              23            26         1        101,46
...      ...             ...           ...       ...           ...
4068   0.010              20            40         0         60,66
4069   6.250              21            28         0         82,36
4070   5.000              23            28         0        105,08
4071   3.010              24            39         0         97,36
4072   2.875              21            41         0         18,87

     Veränderung zum Vortag  ...  Umlaufendes Volumen Emissionswährung  \
0                     1,08%  ...         7.000000e+08              EUR
1                    -0,09%  ...         1.000000e+09              EUR
2                    -0,09%  ...         1.000000e+09              EUR
3                     0,03%  ...         1.000000e+09              EUR
4                     0,03%  ...         1.000000e+09              EUR
...                     ...  ...                  ...              ...
4068                 -0,56%  ...         1.200000e+09              EUR
4069                  0,15%  ...         1.500000e+08              BRL
4070                 -0,04%  ...         2.250000e+09              SEK
4071                  0,15%  ...         1.000000e+07              EUR
4072                  0,00%  ...         7.500000e+08              USD

      Depotwährung Notierungsaufnahme Emission_year_2020.0  \
0              EUR         20,09,2023                False
1              EUR         20,05,2022                False
2              EUR         20,05,2022                False
3              EUR         24,05,2023                False
4              EUR         24,05,2023                False
...            ...                ...                  ...
4068           EUR         23,11,2020                 True
4069           BRL         08,01,2024                False
4070           SEK         07,11,2023                False
4071           EUR         03,05,2024                False
4072           USD         12,07,2021                False

     Emission_year_2021.0 Emission_year_2022.0 Emission_year_2023.0  \
0                   False                False                 True
1                   False                 True                False
2                   False                 True                False
3                   False                False                 True
4                   False                False                 True
...                   ...                  ...                  ...
4068                False                False                False
4069                 True                False                False
4070                False                False                 True
4071                False                False                False
4072                 True                False                False

     Emission_year_2024.0 Emission_year_2025.0
0                   False                False
1                   False                False
2                   False                False
3                   False                False
4                   False                False
...                   ...                  ...
4068                False                False
4069                False                False
4070                False                False
4071                 True                False
4072                False                False

[4073 rows x 36 columns]

In [5]:
# Columns to keep
columns_to_keep = ['ISIN', 'Modified Duration', 'Kupon',
                   'Emittent', 'Branche', 'Fälligkeit', 'Schuldnerkündigungsart',
                   'Sonderkündigung', 'Nachrangig', 'Kleinste handelbare Einheit',
                   'Spezialist', 'Handelsmodell', 'Emissionsdatum', 'Emissionsvolumen',
                   'Umlaufendes Volumen', 'Emissionswährung', 'Depotwährung',
                   'Notierungsaufnahme', 'Emission_year_2020.0', 'Emission_year_2021.0',
                   'Emission_year_2022.0', 'Emission_year_2023.0', 'Emission_year_2024.0',
                   'Emission_year_2025.0']

df_universe_selected = df_universe[columns_to_keep]  # Select only the necessary columns

# Merge
df_merged = df.merge(df_universe_selected, on="ISIN", how="left")
df_merged.drop_duplicates(inplace=True)
print(df_merged)

                        Name Clean_Company_Maturity     WKN  \
0       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
1       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
4       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
5       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
8       E.ON SE 0,375% 20/27    e on se 0 375 20 27  A254QR
...                      ...                    ...     ...
31856  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
31857  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
31858  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
31859  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310
31860  Talanx AG 1,75% 21/42   talanx ag 1 75 21 42  TLX310

                                                     URL          ISIN  \
0      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
1      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
4      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
5      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
8      https://www.boerse-frankfurt.de/anleihe/xs2103...  xs2103014291
...                                                  ...           ...
31856  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
31857  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
31858  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
31859  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693
31860  https://www.boerse-frankfurt.de/anleihe/xs2411...  xs2411241693

         Company Kupon_Maturity  Coupon  Maturity_Start  Maturity_End  ...  \
0        e on se    0 375 20 27   0.375              20            27  ...
1        e on se    0 375 20 27   0.375              20            27  ...
4        e on se    0 375 20 27   0.375              20            27  ...
5        e on se    0 375 20 27   0.375              20            27  ...
8        e on se    0 375 20 27   0.375              20            27  ...
...          ...            ...     ...             ...           ...  ...
31856  talanx ag     1 75 21 42   1.750              21            42  ...
31857  talanx ag     1 75 21 42   1.750              21            42  ...
31858  talanx ag     1 75 21 42   1.750              21            42  ...
31859  talanx ag     1 75 21 42   1.750              21            42  ...
31860  talanx ag     1 75 21 42   1.750              21            42  ...

       Umlaufendes Volumen  Emissionswährung Depotwährung  Notierungsaufnahme  \
0             1.000000e+09               EUR          EUR          14,01,2020
1             1.000000e+09               EUR          EUR          14,01,2020
4             1.000000e+09               EUR          EUR          14,01,2020
5             1.000000e+09               EUR          EUR          14,01,2020
8             1.000000e+09               EUR          EUR          14,01,2020
...                    ...               ...          ...                 ...
31856                  NaN               NaN          NaN                 NaN
31857                  NaN               NaN          NaN                 NaN
31858                  NaN               NaN          NaN                 NaN
31859                  NaN               NaN          NaN                 NaN
31860                  NaN               NaN          NaN                 NaN

      Emission_year_2020.0 Emission_year_2021.0 Emission_year_2022.0  \
0                     True                False                False
1                     True                False                False
4                     True                False                False
5                     True                False                False
8                     True                False                False
...                    ...                  ...                  ...
31856                  NaN                  NaN                  NaN
31857                  NaN                  NaN                  NaN
31858                  NaN                  NaN                  NaN
31859                  NaN                  NaN                  NaN
31860                  NaN                  NaN                  NaN

      Emission_year_2023.0 Emission_year_2024.0 Emission_year_2025.0
0                    False                False                False
1                    False                False                False
4                    False                False                False
5                    False                False                False
8                    False                False                False
...                    ...                  ...                  ...
31856                  NaN                  NaN                  NaN
31857                  NaN                  NaN                  NaN
31858                  NaN                  NaN                  NaN
31859                  NaN                  NaN                  NaN
31860                  NaN                  NaN                  NaN

[17595 rows x 40 columns]

we calculate the YTM for rows that do not have an entry

In [6]:
print(df_merged['Fälligkeit'].head())
print(df_merged['Emissionsdatum'].head())
print(df_merged['DateTime'].head())

0    29,09,2027
1    29,09,2027
4    29,09,2027
5    29,09,2027
8    29,09,2027
Name: Fälligkeit, dtype: object
0    2020-01-16
1    2020-01-16
4    2020-01-16
5    2020-01-16
8    2020-01-16
Name: Emissionsdatum, dtype: object
0    2025-01-02T08:40:00Z
1    2025-01-02T08:40:00Z
4    2025-01-02T10:53:00Z
5    2025-01-02T10:53:00Z
8    2025-01-02T13:47:00Z
Name: DateTime, dtype: object

In [7]:
# Ensure DateTime is parsed, remove timezone and normalize (set time to midnight)
df_merged["Date"] = pd.to_datetime(df_merged["DateTime"]).dt.tz_convert(None).dt.normalize()

# Convert 'Fälligkeit' to datetime using the format provided (tz-naive by default)
df_merged['fälligkeit_datum'] = pd.to_datetime(df_merged['Fälligkeit'], format='%d,%m,%Y')

# Convert 'Emissionsdatum' to datetime (if needed later)
df_merged['emission_datum'] = pd.to_datetime(df_merged['Emissionsdatum'], format='%Y-%m-%d')

# Calculate the exact number of days until maturity
df_merged['days_to_maturity'] = (df_merged['fälligkeit_datum'] - df_merged["Date"]).dt.days

# Face Value assumption (usually 100)
F = 100

# Calculate YTM using the exact days to maturity (converted to years)
def calculate_ytm(row):
    if row["YTM"] == "-":
        P = row["Last Price"]
        C = row["Coupon"]  # Annual coupon payment (assumed to be in percent of F)
        T_years = row["days_to_maturity"] / 365.0  # convert days to years
        if T_years <= 0:
            return None  # handle bonds that have matured or if there's an error
        # YTM approximation formula: (Coupon + (Face Value - Price)/T) / ((Face Value + Price)/2)
        ytm = (C + (F - P) / T_years) / ((F + P) / 2) * 100  # multiplied by 100 to get percentage
        return round(ytm, 2)
    return row["YTM"]

df_merged["YTM"] = df_merged.apply(calculate_ytm, axis=1)

# Display the relevant columns for verification
print(df_merged[["DateTime", "Date", "Last Price", "days_to_maturity", "YTM"]])

                   DateTime       Date  Last Price  days_to_maturity   YTM
0      2025-01-02T08:40:00Z 2025-01-02       94.47            1000.0  2.46
1      2025-01-02T08:40:00Z 2025-01-02       94.47            1000.0  2.46
4      2025-01-02T10:53:00Z 2025-01-02       94.37            1000.0   2.5
5      2025-01-02T10:53:00Z 2025-01-02       94.37            1000.0   2.5
8      2025-01-02T13:47:00Z 2025-01-02       94.44            1000.0  2.47
...                     ...        ...         ...               ...   ...
31856  2025-01-31T08:15:00Z 2025-01-31       86.17               NaN   NaN
31857  2025-01-31T10:00:00Z 2025-01-31       86.27               NaN   NaN
31858  2025-01-31T14:00:00Z 2025-01-31       86.60               NaN   NaN
31859  2025-01-31T15:00:00Z 2025-01-31       86.59               NaN   NaN
31860  2025-01-31T16:00:00Z 2025-01-31       86.69               NaN   NaN

[17595 rows x 5 columns]

In [8]:
df.to_csv('df_final_7.csv', index=False)

# Matching

In [9]:
url = "https://raw.githubusercontent.com/Fijiman001/EGR-Empirical-Project/refs/heads/main/data/Final%20data%20for%20the%20study/df_final_7.csv"
df = pd.read_csv(url)
df

,Name,Clean_Company_Maturity,WKN,URL,ISIN,Company,Kupon_Maturity,Coupon,Maturity_Start,Maturity_End,is_green,Last Price,DateTime,Volume in Euro,+/- %,Currency,YTM
0,"E.ON SE 0,375% 20/27",e on se 0 375 20 27,A254QR,https://www.boerse-frankfurt.de/anleihe/xs2103...,xs2103014291,e on se,0 375 20 27,0.375,20,27,1,94.47,2025-01-02T08:40:00Z,0.0,"0,19",Euro,-
1,"E.ON SE 0,375% 20/27",e on se 0 375 20 27,A254QR,https://www.boerse-frankfurt.de/anleihe/xs2103...,xs2103014291,e on se,0 375 20 27,0.375,20,27,1,94.37,2025-01-02T10:53:00Z,0.0,"0,08",Euro,-
2,"E.ON SE 0,375% 20/27",e on se 0 375 20 27,A254QR,https://www.boerse-frankfurt.de/anleihe/xs2103...,xs2103014291,e on se,0 375 20 27,0.375,20,27,1,94.44,2025-01-02T13:47:00Z,0.0,"0,16",Euro,-
3,"E.ON SE 0,375% 20/27",e on se 0 375 20 27,A254QR,https://www.boerse-frankfurt.de/anleihe/xs2103...,xs2103014291,e on se,0 375 20 27,0.375,20,27,1,94.35,2025-01-03T08:40:00Z,0.0,"0,00",Euro,-
4,"E.ON SE 0,375% 20/27",e on se 0 375 20 27,A254QR,https://www.boerse-frankfurt.de/anleihe/xs2103...,xs2103014291,e on se,0 375 20 27,0.375,20,27,1,94.24,2025-01-03T11:30:00Z,0.0,"-0,11",Euro,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12601,"Talanx AG 1,75% 21/42",talanx ag 1 75 21 42,TLX310,https://www.boerse-frankfurt.de/anleihe/xs2411...,xs2411241693,talanx ag,1 75 21 42,1.750,21,42,1,86.17,2025-01-31T08:15:00Z,0.0,"-0,07",Euro,-
12602,"Talanx AG 1,75% 21/42",talanx ag 1 75 21 42,TLX310,https://www.boerse-frankfurt.de/anleihe/xs2411...,xs2411241693,talanx ag,1 75 21 42,1.750,21,42,1,86.27,2025-01-31T10:00:00Z,0.0,"0,05",Euro,-
12603,"Talanx AG 1,75% 21/42",talanx ag 1 75 21 42,TLX310,https://www.boerse-frankfurt.de/anleihe/xs2411...,xs2411241693,talanx ag,1 75 21 42,1.750,21,42,1,86.60,2025-01-31T14:00:00Z,0.0,"0,43",Euro,-
12604,"Talanx AG 1,75% 21/42",talanx ag 1 75 21 42,TLX310,https://www.boerse-frankfurt.de/anleihe/xs2411...,xs2411241693,talanx ag,1 75 21 42,1.750,21,42,1,86.59,2025-01-31T15:00:00Z,0.0,"0,42",Euro,-
12605,"Talanx AG 1,75% 21/42",talanx ag 1 75 21 42,TLX310,https://www.boerse-frankfurt.de/anleihe/xs2411...,xs2411241693,talanx ag,1 75 21 42,1.750,21,42,1,86.69,2025-01-31T16:00:00Z,0.0,"0,53",Euro,-